micronaut:
  application:
    name: javaRestGrpc

grpc:
  server:
    port: 6004
    keep-alive-time: 5m
    max-inbound-message-size: 64
  channels:
    java-rpc-server:
      address: 'localhost:6005'
      plaintext: true
      max-retry-attempts: 10
